[package]
name = "mdp"
version = "0.1.0"
authors = ["J/A <archer884@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap.git" }
serde = { version = "1.0.123", features = ["derive"] }
toml = "0.5.8"
